<#

  .SYNOPSIS

  Script that will purge remaining .msi and .msp files in windows installs
  from a plan generated by Plan-Cleanup.ps1

  Should be compatible for at least Windows server 2012 using Powershell v3.4

  .PARAMETER ProgramsToDelete

  List of programs to delete, generate using Plan-Cleanup.ps1

  .PARAMETER DryRun

  Do not delete anything, just print what would have been deleted

  .EXAMPLE

  Plan-Cleanup.ps1 | .\Apply-Cleanup.ps1 -DryRun
#>

. .\Types.ps1

params (
  [Parameter(Mandatory = $true, ValueFromPipeline = $true)]
  [Program[]] $ProgramsToDelete,

  [Parameter(Mandatory = $false)]
  [System.Diagnostics.BooleanSwitch] $DryRun = $false
)

# Define delete command to be real or not
# depending on the -DryRun switch
$DeleteCommand = if ($DryRun)
{
  { Param($Item) Write-Host "Would have removed $Item" }
} else
{
  {
    Param($Item)
    Write-Host "Removing $Item"
    # Remove-Item -Path $Item -Force
  }
}

# Execution
foreach ($ProgramToDelete in $ProgramsToDelete)
{
  Write-Host "Cleaning $($ProgramToDelete.Name) patches."
  foreach ($Patch in $ProgramToDelete.Patches)
  {
    Invoke-Expression -Command $DeleteCommand -ArgumentList $Patch.LocalPackage
  }

  Invoke-Expression -Command $DeleteCommand -ArgumentList $ProgramToDelete.LocalPackage
}
